services:
  backend:
    image: hanyujin1022/backend:latest
    container_name: community-backend
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      S3_ACCESS_KEY : ${S3_ACCESS_KEY}
      S3_SECRET_KEY : ${S3_SECRET_KEY}
      AWS_REGION : ${AWS_REGION}
      BUCKET_NAME : ${BUCKET_NAME}

    networks:
      - community_net

networks:
  community_net:
    driver: bridge