services:
  db:
    image: mysql:8.0
    container_name: community-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - community_net

  backend:
    image: hanyujin1022/backend:latest
    container_name: community-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - community_net

  frontend:
    image: hanyujin1022/frontend:latest
    container_name: community-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_URL : ${BACKEND_URL}
    networks:
      - community_net

  nginx:
    image: nginx:latest
    container_name: community-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - community_net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - community_net

volumes:
  db_data:
  portainer_data:

networks:
  community_net:
    driver: bridge